### ISSUE TITLE
Chuckles v1 - Limitless Sensation (OS A)

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1014]
Issue created by: Rhae
  Map reported: Chuckles v1 - Limitless Sensation (OS A)
  Issue:  missing script
  Date: 25/01/2021 17:26:45

**Comment by epbackflip** [comment]
idk why this map was accepted
issue is still there, part cant be passed

**Comment by epbackflip** [comment]
elevators nat working

-Relats'xn
