### ISSUE TITLE
xMinDz* -_v.1_- Let you soul guide you

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1296]
Issue created by: Rhae
  Map reported: xMinDz* -_v.1_- Let you soul guide you
  Issue:  Couldn't read map file.
  Date: 17/02/2021 12:40:21

**Comment by epbackflip** [comment]
check mapfile name in meta for this one for any shit characters, rename mapfile/mapname and close issue

**Comment by Relaxz0r** [comment]
fixed and accepted to OT
