### ISSUE TITLE
StuntPool ft. Danx ft. LooooP - Uhah II

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1315]
Issue created by: Demo
  Map reported: StuntPool ft. Danx ft. LooooP - Uhah II
  Issue:  8 fps in the spawn idk the reason, do we have another version of it? ( it was in os b )
  Date: 19/02/2021 18:45:47

**Comment by epbackflip** [comment]
fix uploadedddddddddddddddddddddddddddddd
