### ISSUE TITLE
Puma - Waves

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1332]
Issue created by: Wolf_Pack
  Map reported: Puma - Waves
  Issue:  There's a part that doesn't work right (on the san andreas map near a trailer park - idk the default map well, sorry xd). It looks like a part that you're supposed to drive upside down in between 2 pieces, but the pieces are missing. Also, no waves. wtf? xd
  Date: 21/02/2021 08:17:20

**Comment by Relaxz0r** [comment]
encrypted server scripts
