### ISSUE TITLE
Puma - Waves II

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1333]
Issue created by: Wolf_Pack
  Map reported: Puma - Waves II
  Issue:  Dinghy part should be edited a little bit. If you do the part normally, it can be painful to see how slowly this part works. It was probably made to work at a different framerate. Also, no waves.
  Date: 21/02/2021 08:39:18

**Comment by Relaxz0r** [comment]
encrypted server scripts
