### ISSUE TITLE
Puma - Mind II [PART I]

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1335]
Issue created by: Wolf_Pack
  Map reported: Puma - Mind II [PART I]
  Issue:  Resource name: DMPuma_-_Mind_II_Part_2 ... Scripts don't work. Maybe they're server-sided if you guys restrict that sort of stuff.
  Date: 21/02/2021 09:10:26

**Comment by Relaxz0r** [comment]
encrypted server scripts
