### ISSUE TITLE
AnUs ft. AixaN ft. TwisteR ft. ReazZon - Waterless Lands

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1507]
Issue created by: SneaX
  Map reported: AnUs ft. AixaN ft. TwisteR ft. ReazZon - Waterless Lands
  Issue:  big ass sc but idk yet where it is
  Date: 20/03/2021 14:30:30

**Comment by Relaxz0r** [comment]
this map is known for having intentially hidden hunter, i dont remember where it was located at, but removed it and accepted the map
