### ISSUE TITLE
[DM] Mohand ft. InferNo - Lets Go 

### ISSUE THREAD

**Issue by qualiti** [Lumiverse/Map-Testing#177]
Issue created by: Automat
      Map reported: [DM] Mohand ft. InferNo - Lets Go 
      Issue:  The shaders inside the map make it unplayable if you're using ultrathing
      Date: 24/11/2020 18:19:50

**Comment by epbackflip** [comment]
on one part, deco has enabled collision and is messing with the part
ultrathing issue sounds like a "you" problem

**Comment by Relaxz0r** [comment]
1. fixed
2. invalid
