### ISSUE TITLE
[DM] CristiaN v2 - TechnoSport II [FIX]

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1853]
Issue created by: CreeX
  Map reported: [DM] CristiaN v2 - TechnoSport II [FIX]
  Issue:  impossible to finish, missing velocity script on a big loop
  Date: 17/06/2021 22:00:40

**Comment by CreeX0rZ** [comment]
will probably be good as OSA but couldn't finish now
