### ISSUE TITLE
Lx ft. GermO ft. SymoN ft. DS - Heatwave

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1861]
Issue created by: djebzer
  Map reported: Lx ft. GermO ft. SymoN ft. DS - Heatwave
  Issue:  missing repair at some point making the map unpassable
  Date: 22/06/2021 21:38:19

**Comment by zjkdev** [comment]
Add it atleast here so it still makes the map hard, because for now it's not passable at all.
![image](https://user-images.githubusercontent.com/35749378/122988592-34dd1980-d3a2-11eb-8f1e-c08a80081247.png)
