### ISSUE TITLE
Torque - Matter

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1944]
Issue created by: CreeX
  Map reported: Torque - Matter
  Issue:  Needs fix, one jump script can throw you into water
  Date: 15/07/2021 23:01:47

**Comment by CreeX0rZ** [comment]
also two car changing scripts aren't working (but maybe intentionally?)

**Comment by Relaxz0r** [comment]
every script is working fine, none were sending me to water :((
