### ISSUE TITLE
sYKu v4 - Band The Rolla

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1951]
Issue created by: CreeX
  Map reported: sYKu v4 - Band The Rolla
  Issue:  SC still open somewhere (?)
  Date: 17/07/2021 15:06:32

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/126037910-263a3e62-c60a-4f86-82b4-9f268ac3b65e.png)
