### ISSUE TITLE
ShondeX ft. BrighT - Blinded in Chains II

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1953]
Issue created by: xARROW
  Map reported: ShondeX ft. BrighT - Blinded in Chains II
  Issue:  big sc on spawnpoint https://streamable.com/plbdbs
  Date: 18/07/2021 09:12:25

**Comment by Relaxz0r** [comment]
Blocked the object you were jumping off of and added script in case u somehow manage to make that cut. If any other cut found - report again.
