### ISSUE TITLE
SandeX ft. Conquer ft. ZinTro - The Sleepless World IV

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#1963]
Issue created by: CreeX
  Map reported: SandeX ft. Conquer ft. ZinTro - The Sleepless World IV
  Issue:  Open SC (?)
  Date: 27/07/2021 11:52:44

**Comment by Relaxz0r** [comment]
what kind of report is this? the hell i know? how do you know tho? theres 0 tops with sc, only real runs, thanks to you i found 4 secs and 14 secs cuts at same part and also secret way to hunter, which is slower and not worth fixing...blocked the cuts i found but next time i aint blocking small cuts -_-
