### ISSUE TITLE
[HDM] ZinC v8 - Conquerer

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2051]
Issue created by **SneaX#1327** on **October 12th, 2021, 11:39:26 GMT+00:00**

Map: [HDM] ZinC v8 - Conquerer
Issue: huge sc

**Comment by epbackflip** [comment]
if i'm not mistaken, similar issue was opened earlier > https://github.com/Lumiverse/Map-Testing/issues/2013
