### ISSUE TITLE
[DM] [DM] Punishable - V1 - Further Revelation

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2053]
Issue created by **CreeX#9004** on **October 15th, 2021, 20:17:33 GMT+00:00**

Map: [DM] [DM] Punishable - V1 - Further Revelation
Issue: big sc + trees with collision in road => Accept as Easy DM

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/137548605-4c3e9a30-b8a6-4d10-b21e-bffb5d1e91a0.png)

Jump through rocks next to invis wall, the trees on screen have collision

**Comment by epbackflip** [comment]
any comment
