### ISSUE TITLE
[DM] SymoN ft. Hooligan - Save Your Skills

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2057]
Issue created by **Backflip#0497** on **October 26th, 2021, 18:08:56 GMT+00:00**

Map: [DM] SymoN ft. Hooligan - Save Your Skills
Issue: palms (accepted)

**Comment by Relaxz0r** [comment]
no fix needed, "decorative" palms dont have to be replaced
