### ISSUE TITLE
[DM] Skotinka v5 - Fast Force

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2062]
Issue created by **Backflip#0497** on **November 9th, 2021, 13:01:09 GMT+00:00**

Map: [DM] Skotinka v5 - Fast Force
Issue: palms mod should be added (accepted)

**Comment by epbackflip** [comment]
and scs still available ffs

**Comment by Relaxz0r** [comment]
scs who care, palms were fixed (palms from spawn non replaceable)
