### ISSUE TITLE
[DM] [DM] Ritual - Never Continue

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2078]
Issue created by **CreeX#9004** on **November 24th, 2021, 17:24:08 GMT+00:00**

Map: [DM] [DM] Ritual - Never Continue
Issue: big cut at ~0:25 + missing song => accept as Easy

**Comment by CreeX0rZ** [comment]
![123](https://user-images.githubusercontent.com/85842850/143286134-bd7918ed-34c7-459a-83fb-2a5ec73c05ee.png)
Go on these loops further forward, rotate and go on second loops (the ones closer on screen)

**Comment by Relaxz0r** [comment]
let the cut be
