### ISSUE TITLE
Martyz v37 - Driftland | stuck on blackscreen at the Elegy upgrade. further script-related issues likely to follow

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#208]
Username: BriaN
Map name: Martyz v37 - Driftland | stuck on blackscreen at the Elegy upgrade. further script-related issues likely to follow

**Comment by Relaxz0r** [comment]
Server-sided scripts are not being supported by the server, also everything is encrypted. Works like clock on local server tho. Will be declined.
