### ISSUE TITLE
[DM] Shine v3 - Dark Ichthyosis

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2090]
Issue created by **CreeX#9004** on **December 13th, 2021, 13:07:09 GMT+00:00**

Map: [DM] Shine v3 - Dark Ichthyosis
Issue: possible sc with Stuntplane

**Comment by CreeX0rZ** [comment]
https://www.youtube.com/watch?v=JcphR872dvY&ab_channel=nzgvrz
