### ISSUE TITLE
[HDM] Pablow ft. Rampage - Skilled Stuntplane II

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2091]
Issue created by **CreeX#9004** on **December 13th, 2021, 13:08:49 GMT+00:00**

Map: [HDM] Pablow ft. Rampage - Skilled Stuntplane II
Issue: possible sc with Stuntplane

**Comment by CreeX0rZ** [comment]
https://www.youtube.com/watch?v=lBLNWRThlic&ab_channel=nzgvrz
