### ISSUE TITLE
[DM] #TREMOR v1 - Psycho

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2092]
Issue created by **CreeX#9004** on **December 17th, 2021, 12:05:00 GMT+00:00**

Map: [DM] #TREMOR v1 - Psycho
Issue: palm with collision in track

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/146542291-a6c8f8f9-f36f-4974-9188-47f5a75f204a.png)
