### ISSUE TITLE
[DM] HeHu v12 - From Here To Forever II

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2097]
Issue created by **SneaX#1337** on **January 1st, 2022, 13:09:28 GMT+00:00**

Map: [DM] HeHu v12 - From Here To Forever II
Issue: Script shoots you way over the nos pickup

**Comment by Relaxz0r** [comment]
no fix needed, https://youtu.be/nHABu8Svfao?t=85
