### ISSUE TITLE
[DM] Miketz ft. Cosa_Nostra - The Good Old Times

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2101]
Issue created by **CreeX#9004** on **January 4th, 2022, 18:18:07 GMT+00:00**

Map: [DM] Miketz ft. Cosa_Nostra - The Good Old Times
Issue: rock in track (accepted)

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/148105203-00eecf56-9c75-4f7e-ade6-dc0206118249.png)
The rock is placed slightly higher above 3rd marker
