### ISSUE TITLE
[HDM] WazeR ft. WondeR ft. Dnts45 ft. FachX - Ghost Skills

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2109]
Issue created by **CreeX#9004** on **January 15th, 2022, 19:59:43 GMT+00:00**

Map: [HDM] WazeR ft. WondeR ft. Dnts45 ft. FachX - Ghost Skills
Issue: song starts after a minute

**Comment by CreeX0rZ** [comment]
(accepted)
