### ISSUE TITLE
[OS] Osnet ft. Storm ft. Chantuu - WoOoW v2

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2114]
Issue created by **Backflip#0497** on **January 27th, 2022, 15:10:38 GMT+00:00**

Map: [OS] Osnet ft. Storm ft. Chantuu - WoOoW v2
Issue: ramp or script missing idk gonna attach ss

**Comment by epbackflip** [comment]
![mta-screen_2022-01-27_16-09-01](https://user-images.githubusercontent.com/75175003/151386618-935a976d-7cdc-4975-9bd8-e63326e3798e.png)

**Comment by Relaxz0r** [comment]
recoded to client-side, added missing spawns,accepted to OS B
![mta-screen_2022-01-27_21-34-18](https://user-images.githubusercontent.com/87805940/151406405-05ae195e-c065-45a2-b716-d4112a146f1d.png)
