### ISSUE TITLE
[DM] BaSzTy ft. ProMoe - Flashback

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2115]
Issue created by **Backflip#0497** on **January 27th, 2022, 22:49:25 GMT+00:00**

Map: [DM] BaSzTy ft. ProMoe - Flashback
Issue: big sc, saves 1 min from time)

**Comment by epbackflip** [comment]
sc is right ahead, after sultan pickup
![mta-screen_2022-01-27_23-48-46](https://user-images.githubusercontent.com/75175003/151456357-f8cc2862-7c6e-4d47-842a-78439dfa718f.png)
![image](https://user-images.githubusercontent.com/75175003/151456479-43baf09c-0a68-4c40-9a48-af8407ad1bb5.png)
