### ISSUE TITLE
[OS] Subzero ft. Gio - Speed in Green

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2121]
Issue created by **CreeX#9004** on **February 2nd, 2022, 15:05:16 GMT+00:00**

Map: [OS] Subzero ft. Gio - Speed in Green
Issue: rocks w/ collision on plasticsgate part ==> move to OSA after fix

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/152180064-a78dda82-bc86-46a5-8acd-52e5e5eacfa5.png)
there are a few of them on whole part
