### ISSUE TITLE
[DM] FS.999.FS v10 - RACERS LAND

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2127]
Issue created by **CreeX#9004** on **February 10th, 2022, 13:10:26 GMT+00:00**

Map: [DM] FS.999.FS v10 - RACERS LAND
Issue: may spawn as CJ

**Comment by CreeX0rZ** [comment]
in case this helps, Quantum v2 was played before

**Comment by Relaxz0r** [comment]
After playing this map for 30 minutes (DM room) bug didnt appear for any player, nor did Quantum v2 affect the map anyhow. Hence it was caused by some other map which had shitly written scripts or server-sided non working stuff :)
