### ISSUE TITLE
[OS] Shark - Accidentally Created

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2144]
Issue created by **Backflip#0497** on **February 25th, 2022, 15:19:42 GMT+01:00**

Map: [OS] Shark - Accidentally Created
Issue: map is probaly missing boat pickups at one part, check #map-reports for ss

**Comment by epbackflip** [comment]
![image](https://user-images.githubusercontent.com/75175003/155741897-9ae74e07-0197-4aca-b910-72ce883ca419.png)
