### ISSUE TITLE
[DM] V4 v1 - Artificial Nocturne

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2168]
Issue created by **CreeX#9004** on **March 29th, 2022, 14:04:36 GMT+02:00**

Map: [DM] V4 v1 - Artificial Nocturne
Issue: One part needs to be reworked before accepting to DM arena (accepted to OT)

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/160607271-228399a7-f840-46c0-9cee-27a4078453e9.png)
Here, you need to line up next to this dark shade, however when driving on this roughly looped light shade, you're getting bounced slightly to the left, which then kills you on the invis part further. After fixing the part, the map could be accepted as Medium, but if not, it is fine for OT (most of the parts are pretty rough/with bad markers).
