### ISSUE TITLE
[DM] MayckeL v3 - Source Of Life

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2170]
Issue created by **CreeX#9004** on **March 29th, 2022, 16:46:01 GMT+02:00**

Map: [DM] MayckeL v3 - Source Of Life
Issue: missing some sort of speed script

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/160638884-e6607a5a-de25-4996-a9b4-b4aae60ec35f.png)
Seems like this map wasn't made in 51 FPS, some parts are slightly off (best example is the spawn), hence it is impossible to pass this part
