### ISSUE TITLE
[OS] RaceXtreme ft. Rock - Escape From Your Bad Mind

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2171]
Issue created by **CreeX#9004** on **March 30th, 2022, 22:19:52 GMT+02:00**

Map: [OS] RaceXtreme ft. Rock - Escape From Your Bad Mind
Issue: unpassable (probably missing hunter)

**Comment by epbackflip** [comment]
![mta-screen_2022-03-30_22-48-16](https://user-images.githubusercontent.com/75175003/160928389-ff3a0f89-14c0-4c9c-82f5-c52a3dd9f3d2.png)

something missing here
