### ISSUE TITLE
[OS] iMeMPlayZ ft. Nipy ft. Shox ft. CIFFON - Ratty Industry

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2177]
Issue created by **DarkyZ#7133** on **April 2nd, 2022, 11:08:23 GMT+02:00**

Map: [OS] iMeMPlayZ ft. Nipy ft. Shox ft. CIFFON - Ratty Industry
Issue: The map has a random spawn in the middle of the water.

**Comment by Relaxz0r** [comment]
duplicated
