### ISSUE TITLE
[DM] Rheinmetall ft. Gerc - Feeling Reckless II

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2184]
Issue created by **CreeX#9004** on **April 17th, 2022, 19:03:45 GMT+02:00**

Map: [DM] Rheinmetall ft. Gerc - Feeling Reckless II
Issue: Object w/ collision on track

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/163724871-42f9b728-5614-4d21-96d7-fcde9901fb54.png)
It's basically at the same altitude as the white deco object, on the right side of the road, getting a slight bump there every time
