### ISSUE TITLE
[DM] CooN ft. AssiL - Brave

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2191]
Issue created by **Backflip#0497** on **April 26th, 2022, 13:28:14 GMT+02:00**

Map: [DM] CooN ft. AssiL - Brave
Issue: objects blocking part of the track (accepted to OT)

**Comment by epbackflip** [comment]
it's this wallride, possibly the shades on the back blocking it

![mta-screen_2022-04-26_13-27-09](https://user-images.githubusercontent.com/75175003/165290308-89512666-1c50-4430-baa6-0848c1302dc5.png)
