### ISSUE TITLE
[DM] XeaT Vol 4 - Resolutions

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2193]
Issue created by **Backflip#0497** on **April 26th, 2022, 13:47:43 GMT+02:00**

Map: [DM] XeaT Vol 4 - Resolutions
Issue: was testing "not good enough" maps, but here there's a jump script not working, ss below

**Comment by epbackflip** [comment]
![mta-screen_2022-04-26_13-47-06](https://user-images.githubusercontent.com/75175003/165293438-eadb44f2-cf61-46f0-b5f1-b021af14f113.png)
