### ISSUE TITLE
[DM] Wintersea ft. XeaT - Coexist

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2194]
Issue created by **Backflip#0497** on **April 26th, 2022, 14:00:04 GMT+02:00**

Map: [DM] Wintersea ft. XeaT - Coexist
Issue: Declined by Danx: Cargobob part is bugged, you hit the roof when getting the vehicle.

**Comment by epbackflip** [comment]
1st cargobob pickup part imo the whole part should be filled with pickups, not just the sides

2nd one was mentioned by Danx, i think if the diagonal shades are removed, the problem will be fixed

![mta-screen_2022-04-26_13-59-24](https://user-images.githubusercontent.com/75175003/165295489-30c84c4c-b9c8-43ee-9cc1-bfc7d6729c8d.png)
