### ISSUE TITLE
[DM] [DM]MusBarca - V5 Project Dream

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2198]
Issue created by **CreeX#9004** on **May 5th, 2022, 12:55:55 GMT+00:00**

Map: [DM] [DM]MusBarca - V5 Project Dream
Issue: bouncy parts throughout the map (ballypllr parts)

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/166927357-29e2e0bc-967c-465b-a725-22e9de4eb6eb.png)

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/166927501-43389a1d-0e66-4613-88ff-3757ea93c7cc.png)
this one is barely passable

**Comment by Relaxz0r** [comment]
passed the map legit 1 try
