### ISSUE TITLE
[DM] M4RkO ft. CarmY - Mysterious Place

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2203]
Issue created by **CreeX#9004** on **May 16th, 2022, 13:01:03 GMT+00:00**

Map: [DM] M4RkO ft. CarmY - Mysterious Place
Issue: Missing song (accepted)

**Comment by CreeX0rZ** [comment]
can be just moved to OT since it's dogshit anyways
