### ISSUE TITLE
[DM] HyPeX ft. SkillZ - Intervalia

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2205]
Issue created by **CreeX#9004** on **May 16th, 2022, 21:17:44 GMT+00:00**

Map: [DM] HyPeX ft. SkillZ - Intervalia
Issue: dark shade causes drift on spawn

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/168684077-110887b0-b3ac-4f50-a621-40492bdb3144.png)
you have about 50% chance to get drifted upon driving on the dark shade

**Comment by Relaxz0r** [comment]
the most retarded report i have ever seen,no fix needed
