### ISSUE TITLE
[DM] iNitreke ft. adeliveR - After All Fall Down

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2216]
Issue created by **CreeX#9004** on **June 20th, 2022, 23:01:04 GMT+00:00**

Map: [DM] iNitreke ft. adeliveR - After All Fall Down
Issue: one bally requires disabled collision

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/174686946-e995f2bd-9c0a-4c31-9090-d1120ebab790.png)
if you drive in front of this bally, you get launched to the sky - the collision seems unnecessary
