### ISSUE TITLE
[FUN] CIFFON - Battle Arena

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2219]
Issue created by **Backflip#0497** on **June 21st, 2022, 20:45:54 GMT+00:00**

Map: [FUN] CIFFON - Battle Arena
Issue: song not working and texture not working on object (will attach ss)

**Comment by epbackflip** [comment]
![mta-screen_2022-06-21_22-45-16](https://user-images.githubusercontent.com/75175003/174894361-d214fa56-8fdf-492f-83f7-741d2570fd1c.png)

accepted it btw
