### ISSUE TITLE
[DM] L!nK ft. Javii ft. Sendy - Walk In The Forest

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2223]
Issue created by **CreeX#9004** on **July 7th, 2022, 10:22:33 GMT+00:00**

Map: [DM] L!nK ft. Javii ft. Sendy - Walk In The Forest
Issue: 40 sec sc (idk where)

**Comment by CreeX0rZ** [comment]
![image](https://user-images.githubusercontent.com/85842850/177751898-c878cd1f-953d-4558-bd05-76694d28da0d.png)
