### ISSUE TITLE
[DM] CooN ft. AssiL - Brave

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2224]
Issue created by **DarkyZ#7133** on **August 12th, 2022, 11:57:10 GMT+00:00**

Map: [DM] CooN ft. AssiL - Brave
Issue: After Pink marker Jump part, invisible needed on the part after it to land, else you fall in the water. It's right after a wall-ride with pink markers.

**Comment by Relaxz0r** [comment]
no fix needed
