### ISSUE TITLE
[DM] Struggle v2 - Locked Out Of Heaven

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#2225]
Issue created by **DarkyZ#7133** on **August 12th, 2022, 12:38:31 GMT+00:00**

Map: [DM] Struggle v2 - Locked Out Of Heaven
Issue: First Slanted Wall-ride part needs to be adjusted, you can hit the edge if you're going middle since no markers.

**Comment by Relaxz0r** [comment]
no fix needed
