### ISSUE TITLE
BeziteX ft. Grimmjow - Crimson Trail

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#309]
Issue created by: Backflip
    Map reported: BeziteX ft. Grimmjow - Crimson Trail
    Issue:  badly placed markers
    Date: 29/11/2020 14:52:06

**Comment by Relaxz0r** [comment]
bad markers(which are actually good) were reported but missing spawns and unreachable hunter were not, excuse moi ?
