### ISSUE TITLE
Kamen v3 - An Improved Shit

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#373]
Issue created by: pascal
    Map reported: Kamen v3 - An Improved Shit
    Issue:  sc to hunter mid map
    Date: 02/12/2020 15:17:09

**Comment by CreeX0rZ** [comment]
Missing billboard script (accepted)

**Comment by epbackflip** [comment]
arrow billboards and FFS billboards on one part are working for me, if there are any other which are not working, pls reopen and detail them
