### ISSUE TITLE
Daan ft. LG - Infinity Jumps

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#433]
Issue created by: Backflip
    Map reported: Daan ft. LG - Infinity Jumps
    Issue:  remove the rock on first jump with comet or disable collision; track is missing in the next part (cant test the whole map but i assume its OS B)
    Date: 05/12/2020 14:05:42

**Comment by Relaxz0r** [comment]
no track is missing, just server scripts not working :DD
