### ISSUE TITLE
Himmelblau by DeltaForce

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#504]
Issue created by: Backflip
    Map reported: Himmelblau by DeltaForce
    Issue:  missing a repair pickup after bmx part to inf; 32 spawns (no room for them)
    Date: 08/12/2020 11:07:09

**Comment by epbackflip** [comment]
spawns were added, but now after passing spawn track is missin
![mta-screen_2022-04-09_16-43-29](https://user-images.githubusercontent.com/75175003/162579078-5f9d2a2d-5a47-4d40-b4b9-78e7da2c6f76.png)
g

**Comment by Relaxz0r** [comment]
returend tracks, added repair, no place for spawns > OT
