### ISSUE TITLE
Itoko ft. Osnet - Desert Rock

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#558]
Issue created by: Wolf_Pack
    Map reported: Itoko ft. Osnet - Desert Rock
    Issue:  One of the scripts doesn't work. There's a flying part with an infernus, but there's nothing but a dead end after that. (judging from what I saw, it's os a)
    Date: 11/12/2020 05:30:11

**Comment by Relaxz0r** [comment]
https://youtu.be/-PMX77EgdpE?t=69
