### ISSUE TITLE
Itoko v3 - Under The Moon

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#561]
Issue created by: Wolf_Pack
    Map reported: Itoko v3 - Under The Moon
    Issue:  Too many shortcuts. You can skip every wallride and loop (and at least one ramp) (os a)
    Date: 11/12/2020 06:12:31

**Comment by Relaxz0r** [comment]
that map is in OS B currently, let those cuts exist (could be fixed in future if there are some major ones)
