### ISSUE TITLE
[DM] Nemo vol.2 - Miyoki

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#587]
Issue created by: Atomix
    Map reported: [DM] Nemo vol.2 - Miyoki
    Issue:  unclear instructions throughout the whole map
    Date: 13/12/2020 15:56:40

**Comment by Relaxz0r** [comment]
uNcLeAr InStRuCtIoNs thRoUgHoUt ThE wHoLe MaP
