### ISSUE TITLE
DonJohn ft. SupRime - Time Travel

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#646]
Issue created by: Backflip
  Map reported: DonJohn ft. SupRime - Time Travel
  Issue:  on Stony Landscape map's part, close to the end of the map (the waterjump part) collision isn't disabled and a rock is getting in the way of the track, cant pass the part unless i do some magic kontrol steering (OS A)
  Date: 19/12/2020 15:36:14

**Comment by Relaxz0r** [comment]
its made exactly the same way on original map, fixed
