### ISSUE TITLE
SE-15 by F-22

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#661]
Issue created by: Backflip
  Map reported: SE-15 by F-22
  Issue:  script isnt working
  Date: 21/12/2020 02:21:21

**Comment by Relaxz0r** [comment]
that was broken actionscript but magically replacing doesnt help, also any script i add to the map doesnt work,hell knows whats wrong, maybe cos encrypted scripts have an impact or smtng, works on local tho
