### ISSUE TITLE
Morning after DarK - Feche

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#663]
Issue created by: Backflip
  Map reported: Morning after DarK - Feche
  Issue:  after caddy pickup (after the wallride) a bullet pickup is hidden underneath a rock and is barely visible, i think a marker or an arrow should be placed above it (OS A)
  Date: 21/12/2020 16:24:01

**Comment by Relaxz0r** [comment]
maybe,but...https://youtu.be/BdRQJisfMtw?t=219
