### ISSUE TITLE
JohnY - Alive 'till I Die IV

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#665]
Issue created by: Atomix
  Map reported: JohnY - Alive 'till I Die IV
  Issue:  2 diff. huge shortcuts to hunter
  Date: 21/12/2020 21:55:02

**Comment by Relaxz0r** [comment]
uploaded latest johny's fix of the map which includes shortcuts fixing and track improvements, report again if large shortcuts are possible
