### ISSUE TITLE
RaZoR V.8 - Misery

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#735]
Issue created by: Backflip
  Map reported: RaZoR V.8 - Misery
  Issue:  on the part where you have to slow down and turn to take nos, i believe most of ppl will activate it immediately but it shouldnt be activated, place nos on the start of the loop (OS A)
  Date: 26/12/2020 15:21:06

**Comment by brianmta** [comment]
no fix needed
