### ISSUE TITLE
[DM] AlcatrazZ ft. L!nK ft. CristiaN - Follow The Light

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#798]
Issue created by: Rhae
  Map reported: [DM] AlcatrazZ ft. L!nK ft. CristiaN - Follow The Light
  Issue:  skybox not working
  Date: 01/01/2021 18:18:15

**Comment by Relaxz0r** [comment]
hell knows, it just refuses to work on the server
