### ISSUE TITLE
[DM] TonyxO ft. BurNouT ft. Driver - POLAR EXPRESS

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#802]
Issue created by: Atomix
  Map reported: [DM] TonyxO ft. BurNouT ft. Driver - POLAR EXPRESS
  Issue:  fps issues throughout the map caused by modded objects
  Date: 02/01/2021 12:45:55

**Comment by Relaxz0r** [comment]
130 replaced objects, let it stay in ot
